1. Exercise on Functions:
a. Create a Python program that converts between different units of measurement.
-Prompt the user to choose the type of conversion (length, weight, volume).
-Ask the user to input the value to be converted.
-Perform the conversion and display the result.
-Handle potential errors.
-Implement functions for conversions and include docstrings.

In [21]:
def convert_length(value, unit_from, unit_to):
    """Convert between different units of length."""
    conversion_rates = {'meters': 1, 'kilometers': 0.001, 'centimeters': 100, 'inches': 39.37}
    return value * conversion_rates[unit_to] / conversion_rates[unit_from]

def convert_weight(value, unit_from, unit_to):
    """Convert between different units of weight."""
    conversion_rates = {'grams': 1, 'kilograms': 0.001, 'pounds': 0.00220462}
    return value * conversion_rates[unit_to] / conversion_rates[unit_from]

def convert_volume(value, unit_from, unit_to):
    """Convert between different units of volume."""
    conversion_rates = {'liters': 1, 'milliliters': 1000, 'gallons': 0.264172}
    return value * conversion_rates[unit_to] / conversion_rates[unit_from]

def unit_conversion():
    """Main function to perform unit conversions."""
    try:
        conversion_type = input("Choose a conversion type (length, weight, volume): ").lower()
        value = float(input("Enter the value to be converted: "))
        unit_from = input("Enter the unit to convert from: ").lower()
        unit_to = input("Enter the unit to convert to: ").lower()

        if conversion_type == 'length':
            result = convert_length(value, unit_from, unit_to)
        elif conversion_type == 'weight':
            result = convert_weight(value, unit_from, unit_to)
        elif conversion_type == 'volume':
            result = convert_volume(value, unit_from, unit_to)
        else:
            raise ValueError("Invalid conversion type")
        
        print(f"{value} {unit_from} is equal to {result} {unit_to}")

    except ValueError as e:
        print(f"Error: {e}")

unit_conversion()


Choose a conversion type (length, weight, volume):  weight
Enter the value to be converted:  50000
Enter the unit to convert from:  grams
Enter the unit to convert to:  kilograms


50000.0 grams is equal to 50.0 kilograms


b.Create a Python program that performs various mathematical operations on a list of numbers.
Prompt the user to choose an operation (sum, average, maximum, or minimum).
Ask the user to input a list of numbers.
Perform the selected operation and display the result.
Handle potential errors.
Implement functions for each operation.


In [23]:
def calculate_sum(numbers):
    return sum(numbers)

def calculate_average(numbers):
    if len(numbers) == 0:
        raise ValueError("Cannot calculate average of an empty list.")
    return sum(numbers) / len(numbers)

def calculate_maximum(numbers):
    if len(numbers) == 0:
        raise ValueError("Cannot find maximum of an empty list.")
    return max(numbers)

def calculate_minimum(numbers):
    if len(numbers) == 0:
        raise ValueError("Cannot find minimum of an empty list.")
    return min(numbers)

def main():
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")
    try:
        operation_choice = int(input("Enter the number corresponding to your choice (1-4): "))
        if operation_choice not in [1, 2, 3, 4]:
            print("Invalid choice. Please enter a number between 1 and 4.")
            return
        numbers_input = input("Enter a list of numbers separated by spaces: ")
        numbers = list(map(float, numbers_input.split()))
        if operation_choice == 1:
            result = calculate_sum(numbers)
            print(f"The sum of the numbers is: {result}")
        elif operation_choice == 2:
            result = calculate_average(numbers)
            print(f"The average of the numbers is: {result}")
        elif operation_choice == 3:
            result = calculate_maximum(numbers)
            print(f"The maximum number is: {result}")
        elif operation_choice == 4:
            result = calculate_minimum(numbers)
            print(f"The minimum number is: {result}")
    except ValueError as ve:
        print(f"Error: {ve}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()


Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum


Enter the number corresponding to your choice (1-4):  3
Enter a list of numbers separated by spaces:  4 5 2 1 1 1 1 1


The maximum number is: 5.0


2. Exercise on List Manipulation:
Extract Every Other Element:
a. Write a function extract_every_other(lst) that extracts every other element from a list.
Slice a Sublist:

In [31]:
def extract_every_other(lst):
    return lst[::2]

def slice_sublist(lst, start, end):
    return lst[start:end]

list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
result1 = extract_every_other(list)
print(f"Every other element: {result1}")
result2 = slice_sublist(list, 2, 5)
print(f"Sliced sublist: {result2}")


Every other element: [1, 3, 5, 7, 9]
Sliced sublist: [3, 4, 5]


b. Write a function get_sublist(lst, start, end) that returns a sublist between given indices.
Reverse a List Using Slicing:

In [37]:
sublist_result = get_sublist(my_list, 1, 9)
print(f"Sublist from index 1 to 9: {sublist_result}")
reversed_list = reverse_list(my_list)
print(f"Reversed list: {reversed_list}")


Sublist from index 1 to 9: [2, 3, 4, 5, 6, 7, 8, 9]
Reversed list: [9, 8, 7, 6, 5, 4, 3, 2, 1]


c. Write a function reverse_list(lst) that reverses a list using slicing.
Remove the First and Last Elements:

In [41]:
def reverse_list(lst):
    return lst[::-1]

def remove_first_and_last(lst):
    return lst[1:-1]

reversed_list = reverse_list(my_list)
print(f"Reversed list: {reversed_list}")
modified_list = remove_first_and_last(my_list)
print(f"List after removing first and last elements: {modified_list}")


Reversed list: [9, 8, 7, 6, 5, 4, 3, 2, 1]
List after removing first and last elements: [2, 3, 4, 5, 6, 7, 8]


d. Write a function remove_first_last(lst) that removes the first and last elements of a list.
Get the First n Elements:

In [43]:
def remove_first_last(lst):
    return lst[1:-1]

def get_first_n_elements(lst, n):
    return lst[:n]

new_list = remove_first_last(list)
print(f"List after removing first and last elements: {new_list}")
first_n_elements = get_first_n_elements(list, 4)
print(f"First 4 elements: {first_n_elements}")


List after removing first and last elements: [2, 3, 4, 5, 6, 7, 8]
First 4 elements: [1, 2, 3, 4]


e. Write a function get_first_n(lst, n) that extracts the first n elements from a list.
Extract Elements from the End:

In [45]:
def get_first_n(lst, n):
    return lst[:n]

def extract_elements_from_end(lst, n):
    return lst[-n:]

first_n_elements = get_first_n(list, 4)
print(f"First 4 elements: {first_n_elements}")
last_n_elements = extract_elements_from_end(list, 3)
print(f"Last 3 elements: {last_n_elements}")

First 4 elements: [1, 2, 3, 4]
Last 3 elements: [7, 8, 9]


f. Write a function get_last_n(lst, n) that extracts the last n elements.
Extract Elements in Reverse Order:

In [47]:
def get_last_n(lst, n):
    return lst[-n:]

def extract_elements_in_reverse(lst):
    return lst[::-1]
    
last_n_elements = get_last_n(list, 3)
print(f"Last 3 elements: {last_n_elements}")
reversed_elements = extract_elements_in_reverse(list)
print(f"Elements in reverse order: {reversed_elements}")

Last 3 elements: [7, 8, 9]
Elements in reverse order: [9, 8, 7, 6, 5, 4, 3, 2, 1]


g. Write a function reverse_skip(lst) that extracts every second element starting from the second-to-last.

In [49]:
def reverse_skip(lst):
    return lst[-2::-2]
    
list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
result = reverse_skip(list)
print(f"Every second element starting from the second-to-last: {result}")


Every second element starting from the second-to-last: [8, 6, 4, 2]


3. Exercise on Nested List:
a. Flatten a Nested List:

In [1]:
import numpy as np

def flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

nested_list = [1, [2, 3, [4, 5]], 6, [7, [8, 9]]]
flattened_list = flatten(nested_list)
print("Flattened list:", flattened_list)


Flattened list: [1, 2, 3, 4, 5, 6, 7, 8, 9]


b. Write a function flatten(lst) that converts a nested list into a single-level list.
Access Nested List Elements:

In [3]:
import numpy as np

def flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst

nested_list = [1, [2, 3, [4, 5]], 6, [7, [8, 9]]]
flattened_list = flatten(nested_list)
print("Flattened list:", flattened_list)
indices = [1, 2, 0]  
accessed_element = access_nested_element(nested_list, indices)
print("Accessed nested element:", accessed_element)


Flattened list: [1, 2, 3, 4, 5, 6, 7, 8, 9]
Accessed nested element: 4


c. Write a function access_nested_element(lst, indices) that retrieves a specific element using index positions.
Sum of All Elements in a Nested List:

In [5]:
import numpy as np

def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst

def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

nested_list = [1, [2, 3, [4, 5]], 6, [7, [8, 9]]]
indices = [1, 2, 0]
accessed_element = access_nested_element(nested_list, indices)
print("Accessed nested element:", accessed_element)

total_sum = sum_nested(nested_list)
print("Sum of all elements in the nested list:", total_sum)


Accessed nested element: 4
Sum of all elements in the nested list: 45


d. Write a function sum_nested(lst) that computes the sum of all numbers in a nested list.
Remove Specific Elements from a Nested List:

In [7]:
import numpy as np

def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

def remove_element(lst, elem):
    return [remove_element(item, elem) if isinstance(item, list) else item for item in lst if item != elem]

nested_list = [1, [2, 3, [4, 5]], 6, [7, [8, 9]]]
total_sum = sum_nested(nested_list)
print("Sum of all elements in the nested list:", total_sum)

modified_list = remove_element(nested_list, 5)
print("List after removing element 5:", modified_list)


Sum of all elements in the nested list: 45
List after removing element 5: [1, [2, 3, [4]], 6, [7, [8, 9]]]


e. Write a function remove_element(lst, elem) that removes all occurrences of a given element.
Find the Maximum Element in a Nested List:

In [9]:
import numpy as np

def remove_element(lst, elem):
    return [remove_element(item, elem) if isinstance(item, list) else item for item in lst if item != elem]

def find_max(lst):
    max_elem = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_elem = max(max_elem, find_max(item))
        else:
            max_elem = max(max_elem, item)
    return max_elem

nested_list = [1, [2, 3, [4, 5]], 6, [7, [8, 9]]]
modified_list = remove_element(nested_list, 5)
print("List after removing element 5:", modified_list)

max_element = find_max(nested_list)
print("Maximum element in the nested list:", max_element)


List after removing element 5: [1, [2, 3, [4]], 6, [7, [8, 9]]]
Maximum element in the nested list: 9


f. Write a function find_max(lst) that finds the maximum element.
Count Occurrences of an Element in a Nested List:

In [11]:
import numpy as np

def find_max(lst):
    max_elem = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_elem = max(max_elem, find_max(item))
        else:
            max_elem = max(max_elem, item)
    return max_elem

def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

nested_list = [1, [2, 3, [4, 5]], 6, [7, [8, 9]]]
max_element = find_max(nested_list)
print("Maximum element in the nested list:", max_element)

occurrences = count_occurrences(nested_list, 3)
print("Occurrences of element 3 in the nested list:", occurrences)


Maximum element in the nested list: 9
Occurrences of element 3 in the nested list: 1


g. Write a function count_occurrences(lst, elem) that counts occurrences of an element.
Flatten a List of Lists of Lists:

In [13]:
import numpy as np

def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

nested_list = [1, [2, 3, [4, 5]], 6, [7, [8, 9]]]
occurrences = count_occurrences(nested_list, 3)
print("Occurrences of element 3 in the nested list:", occurrences)

deep_flattened_list = deep_flatten(nested_list)
print("Flattened list of lists of lists:", deep_flattened_list)


Occurrences of element 3 in the nested list: 1
Flattened list of lists of lists: [1, 2, 3, 4, 5, 6, 7, 8, 9]


h. Write a function deep_flatten(lst) that flattens deeply nested lists.
Nested List Average:

In [15]:
import numpy as np

def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

def average_nested(lst):
    total = 0
    count = 0
    for item in lst:
        if isinstance(item, list):
            total_sum, item_count = average_nested(item)
            total += total_sum
            count += item_count
        else:
            total += item
            count += 1
    return total, count

nested_list = [1, [2, 3, [4, 5]], 6, [7, [8, 9]]]
flattened_list = deep_flatten(nested_list)
print("Flattened list of deeply nested lists:", flattened_list)

total, count = average_nested(nested_list)
average = total / count if count != 0 else 0
print("Average of all elements in the nested list:", average)


Flattened list of deeply nested lists: [1, 2, 3, 4, 5, 6, 7, 8, 9]
Average of all elements in the nested list: 5.0


i. Write a function average_nested(lst) that computes the average of all elements

4. Exercise on NumPy:
a. Array Creation:
-Initialize an empty 2x2 array.
-Initialize an all-ones 4x2 array.
-Create an array filled with a specific value.
-Convert a list to a NumPy array.

In [93]:
import numpy as np

# 1. Initialize an Empty 2x2 Array
empty_array = np.empty((0, 0))
print("Empty 2x2 array:")
print(empty_array)

# 2. Initialize an All-Ones 4x2 Array
ones_array = np.ones((4, 2))
print("\nAll-ones 4x2 array:")
print(ones_array)

# 3. Create an Array Filled with a Specific Value (7)
value_array = np.full((3, 3), 7)
print("\nArray filled with a specific value (7):")
print(value_array)

# 4. Convert a List to a NumPy Array
my_list = [1, 2, 3, 4]
numpy_array = np.array(my_list)
print("\nConverted NumPy array from list:")
print(numpy_array)


Empty 2x2 array:
[]

All-ones 4x2 array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with a specific value (7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Converted NumPy array from list:
[1 2 3 4]


b.Array Manipulation:
-Create an array with values from 10 to 49.
-Create a 3x3 matrix with values from 0 to 8.
-Create a 3x3 identity matrix.
-Generate a random array of size 30 and compute its mean.
-Create a 10x10 random array and find the min and max values.


In [1]:
import numpy as np
array_10_to_49 = np.arange(10, 50)
print("Array with values from 10 to 49:")
print(array_10_to_49)

matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix with values from 0 to 8:")
print(matrix_3x3)

identity_matrix = np.eye(3)
print("\n3x3 identity matrix:")
print(identity_matrix)

random_array = np.random.rand(30)
mean_value = random_array.mean()
print("\nRandom array of size 30:")
print(random_array)
print(f"Mean of the random array: {mean_value}")
random_10x10 = np.random.rand(10, 10)

min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 random array:")
print(random_10x10)
print(f"Min value: {min_value}")
print(f"Max value: {max_value}")


Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
[0.13604029 0.72713256 0.76546426 0.82023342 0.46581976 0.28285196
 0.95840775 0.97573532 0.33296019 0.20843419 0.83973915 0.14646825
 0.87994274 0.04094337 0.90824729 0.62810689 0.29169373 0.9022157
 0.56950201 0.86431681 0.93924886 0.12881331 0.36268052 0.15618473
 0.30951882 0.22879903 0.62731186 0.72304661 0.03325869 0.12707155]
Mean of the random array: 0.512672986554382

10x10 random array:
[[0.29683863 0.51009603 0.94716552 0.80193239 0.42460073 0.25991585
  0.78598447 0.68244536 0.83937846 0.45938582]
 [0.59532087 0.44872299 0.89789008 0.88797476 0.31473637 0.63566477
  0.8565172  0.5741027  0.85972346 0.65854665]
 [0.63109307 0.5090245  0.18399285 0.49574416 0.11408557 0.36138

c. Array Operations:
Perform addition, subtraction, multiplication, and dot product on given arrays.
Matrix Operations:
Prove mathematical properties using NumPy (e.g., 
𝐴
⋅
𝐴
−
1
=
𝐼
A⋅A 
−1
 =I).
NumPy Performance Comparison:

Compare performance of element-wise operations and matrix multiplications using Python lists vs NumPy arrays.

In [1]:
import numpy as np
import time

array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

addition_result = array_a + array_b
print("Addition result:", addition_result)

subtraction_result = array_a - array_b
print("Subtraction result:", subtraction_result)

multiplication_result = array_a * array_b
print("Multiplication result:", multiplication_result)

dot_product_result = np.dot(array_a, array_b)
print("Dot product result:", dot_product_result)

A = np.array([[4, 7], [2, 6]])

A_inv = np.linalg.inv(A)

identity_matrix = np.dot(A, A_inv)
print("\nA * A_inv = I (Identity Matrix):")
print(identity_matrix)

size = 1000
list_a = [[i for i in range(size)] for _ in range(size)]
list_b = [[i for i in range(size)] for _ in range(size)]

np_array_a = np.array(list_a)
np_array_b = np.array(list_b)

start_time = time.time()
list_add_result = [[list_a[i][j] + list_b[i][j] for j in range(size)] for i in range(size)]
list_add_time = time.time() - start_time

start_time = time.time()
np_add_result = np_array_a + np_array_b
np_add_time = time.time() - start_time

start_time = time.time()
list_matrix_mult_result = [[sum(list_a[i][k] * list_b[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
list_matrix_mult_time = time.time() - start_time

start_time = time.time()
np_matrix_mult_result = np.dot(np_array_a, np_array_b)
np_matrix_mult_time = time.time() - start_time

print(f"\nElement-wise addition with Python lists took: {list_add_time:.6f} seconds")
print(f"Element-wise addition with NumPy took: {np_add_time:.6f} seconds")

print(f"Matrix multiplication with Python lists took: {list_matrix_mult_time:.6f} seconds")
print(f"Matrix multiplication with NumPy took: {np_matrix_mult_time:.6f} seconds")


Addition result: [5 7 9]
Subtraction result: [-3 -3 -3]
Multiplication result: [ 4 10 18]
Dot product result: 32

A * A_inv = I (Identity Matrix):
[[1. 0.]
 [0. 1.]]


KeyboardInterrupt: 